### ISSUE TITLE
Kill/Death Stats not updating

### ISSUE THREAD

**Issue by lorentedford** [msburgess3200/Babstats-Panel#1]
Greetings I am working on a project for VoW and noticed that the Kill/Death Stats were not updating correctly was wondering if their is new directions that needs to be followed since most of these files have been updated. 

Here is an example

http://vowstats.ltcraft.net/index.php?action=kill_stats

The server information though appears ok here.

http://vowstats.ltcraft.net/index.php?action=servers&id=7

**Comment by msburgess3200** [comment]
Most problems lying with this script is due to a lack of memory with PHP. I am working on this and will need time to find where the memory leak is occurring. Once I have found it, I will update this repo.
Regardless  of how much RAM/Memory you allow PHP to use, PHP will detect the problem but not report it and shutdown the script from updating. Like I said, you and VoW are not the only ones to have this issue and I am working on it.

-- on another note --
Also, and fair warning, the "Babstats Panel" is licensed by the GNU. You cannot rebuild these stats without written permissions from the owner. (Me).
You are, however, allowed to use and run said scripts. You are not allowed to modify said scripts without written permission from the owner, unless directed to do so via instructions or installer.
For more information visit: [LICENSE](https://raw.githubusercontent.com/msburgess3200/Babstats-Panel/master/LICENSE)

**Comment by lorentedford** [comment]
THis is still an issue with Stats not uploading.. Please reach out to me at loren@lorentedford.com Would also like the Babstat server client along with updates.. I want to take a look at the whole picture before I start working on this project to bring this back to a working and usable code.. I suppose If its not workable with your code we may just have to rewrite it by hand which at this point is what I have considered if things keep going the way they are going..
